// AUTO-GENERATED by colori-wasm/build.rs — do not edit by hand
import type { Card, SellCard, Color, AnyCardData, DyeCardData, BasicDyeCardData, MaterialCardData, ActionCardData, SellCardData } from './types';

export const DYE_CARDS: DyeCardData[] = [
  {
    kind: 'dye',
    name: 'Kermes',
    colors: ['Red', 'Red', 'Red'],
    ability: { type: 'destroyCards' },
  },
  {
    kind: 'dye',
    name: 'Weld',
    colors: ['Yellow', 'Yellow', 'Yellow'],
    ability: { type: 'destroyCards' },
  },
  {
    kind: 'dye',
    name: 'Woad',
    colors: ['Blue', 'Blue', 'Blue'],
    ability: { type: 'destroyCards' },
  },
  {
    kind: 'dye',
    name: 'Lac',
    colors: ['Red', 'Red', 'Yellow'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Brazilwood',
    colors: ['Red', 'Red', 'Blue'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Pomegranate',
    colors: ['Yellow', 'Yellow', 'Red'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Sumac',
    colors: ['Yellow', 'Yellow', 'Blue'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Elderberry',
    colors: ['Blue', 'Blue', 'Red'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Turnsole',
    colors: ['Blue', 'Blue', 'Yellow'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Madder',
    colors: ['Orange', 'Red'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Turmeric',
    colors: ['Orange', 'Yellow'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Dyer\'s Greenweed',
    colors: ['Green', 'Yellow'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Verdigris',
    colors: ['Green', 'Blue'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Orchil',
    colors: ['Purple', 'Red'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Logwood',
    colors: ['Purple', 'Blue'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Vermilion',
    colors: ['Vermilion'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Saffron',
    colors: ['Amber'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Persian Berries',
    colors: ['Chartreuse'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Azurite',
    colors: ['Teal'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Indigo',
    colors: ['Indigo'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Cochineal',
    colors: ['Magenta'],
    ability: { type: 'sell' },
  },
];

export const MATERIAL_CARDS: MaterialCardData[] = [
  {
    kind: 'material',
    name: 'Ceramics',
    materialTypes: ['Ceramics'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'material',
    name: 'Paintings',
    materialTypes: ['Paintings'],
    ability: { type: 'workshop', count: 4 },
  },
  {
    kind: 'material',
    name: 'Textiles',
    materialTypes: ['Textiles'],
    ability: { type: 'workshop', count: 2 },
  },
];

export const DRAFT_MATERIAL_CARDS: MaterialCardData[] = [
  {
    kind: 'material',
    name: 'Terra Cotta',
    materialTypes: ['Ceramics'],
    color: 'Red',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Ochre Ware',
    materialTypes: ['Ceramics'],
    color: 'Yellow',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Cobalt Ware',
    materialTypes: ['Ceramics'],
    color: 'Blue',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Cinnabar & Canvas',
    materialTypes: ['Paintings'],
    color: 'Red',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Orpiment & Canvas',
    materialTypes: ['Paintings'],
    color: 'Yellow',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Ultramarine & Canvas',
    materialTypes: ['Paintings'],
    color: 'Blue',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Alizarin & Fabric',
    materialTypes: ['Textiles'],
    color: 'Red',
    colorCount: 2,
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Fustic & Fabric',
    materialTypes: ['Textiles'],
    color: 'Yellow',
    colorCount: 2,
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Pastel & Fabric',
    materialTypes: ['Textiles'],
    color: 'Blue',
    colorCount: 2,
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Clay & Canvas',
    materialTypes: ['Ceramics', 'Paintings'],
    ability: { type: 'sell' },
  },
  {
    kind: 'material',
    name: 'Clay & Fabric',
    materialTypes: ['Ceramics', 'Textiles'],
    ability: { type: 'sell' },
  },
  {
    kind: 'material',
    name: 'Canvas & Fabric',
    materialTypes: ['Paintings', 'Textiles'],
    ability: { type: 'sell' },
  },
];

export const BASIC_DYE_CARDS: BasicDyeCardData[] = [
  {
    kind: 'basicDye',
    name: 'Basic Red',
    color: 'Red',
    ability: { type: 'sell' },
  },
  {
    kind: 'basicDye',
    name: 'Basic Yellow',
    color: 'Yellow',
    ability: { type: 'sell' },
  },
  {
    kind: 'basicDye',
    name: 'Basic Blue',
    color: 'Blue',
    ability: { type: 'sell' },
  },
];

export const ACTION_CARDS: ActionCardData[] = [
  {
    kind: 'action',
    name: 'Alum',
    ability: { type: 'destroyCards' },
    workshopAbilities: [{ type: 'gainDucats', count: 1 }],
  },
  {
    kind: 'action',
    name: 'Cream of Tartar',
    ability: { type: 'destroyCards' },
    workshopAbilities: [{ type: 'drawCards', count: 3 }],
  },
  {
    kind: 'action',
    name: 'Gum Arabic',
    ability: { type: 'destroyCards' },
    workshopAbilities: [{ type: 'gainSecondary' }],
  },
  {
    kind: 'action',
    name: 'Potash',
    ability: { type: 'drawCards', count: 2 },
    workshopAbilities: [{ type: 'workshop', count: 3 }],
  },
  {
    kind: 'action',
    name: 'Linseed Oil',
    ability: { type: 'destroyCards' },
    workshopAbilities: [{ type: 'mixColors', count: 2 }],
  },
  {
    kind: 'action',
    name: 'Vinegar',
    ability: { type: 'destroyCards' },
    workshopAbilities: [{ type: 'changeTertiary' }],
  },
];

export const PRIMARIES: Color[] = ['Red', 'Yellow', 'Blue'];
export const SECONDARIES: Color[] = ['Orange', 'Green', 'Purple'];
export const TERTIARIES: Color[] = ['Vermilion', 'Amber', 'Chartreuse', 'Teal', 'Indigo', 'Magenta'];

export const CHALK_CARD: ActionCardData = {
  kind: 'action',
  name: 'Chalk',
  ability: { type: 'sell' },
  workshopAbilities: [{ type: 'gainPrimary' }],
};

export const SELL_CARDS: SellCardData[] = [
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Vermilion'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Amber'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Chartreuse'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Teal'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Indigo'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Magenta'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Orange', 'Red'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Orange', 'Yellow'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Orange', 'Blue'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Green', 'Red'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Green', 'Yellow'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Green', 'Blue'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Purple', 'Red'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Purple', 'Yellow'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Purple', 'Blue'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Red', 'Red', 'Red'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Yellow', 'Yellow', 'Yellow'] },
  { kind: 'sellCard', ducats: 2, requiredMaterial: 'Textiles', colorCost: ['Blue', 'Blue', 'Blue'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Vermilion', 'Red'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Vermilion', 'Yellow'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Vermilion', 'Blue'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Amber', 'Red'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Amber', 'Yellow'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Amber', 'Blue'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Chartreuse', 'Red'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Chartreuse', 'Yellow'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Chartreuse', 'Blue'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Teal', 'Red'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Teal', 'Yellow'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Teal', 'Blue'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Indigo', 'Red'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Indigo', 'Yellow'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Indigo', 'Blue'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Magenta', 'Red'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Magenta', 'Yellow'] },
  { kind: 'sellCard', ducats: 3, requiredMaterial: 'Ceramics', colorCost: ['Magenta', 'Blue'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Vermilion', 'Orange'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Vermilion', 'Green'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Vermilion', 'Purple'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Amber', 'Orange'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Amber', 'Green'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Amber', 'Purple'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Chartreuse', 'Orange'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Chartreuse', 'Green'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Chartreuse', 'Purple'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Teal', 'Orange'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Teal', 'Green'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Teal', 'Purple'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Indigo', 'Orange'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Indigo', 'Green'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Indigo', 'Purple'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Magenta', 'Orange'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Magenta', 'Green'] },
  { kind: 'sellCard', ducats: 4, requiredMaterial: 'Paintings', colorCost: ['Magenta', 'Purple'] },
];

const CARD_LOOKUP: Record<string, AnyCardData> = {};

CARD_LOOKUP['BasicRed'] = { kind: 'basicDye', name: 'Basic Red', color: 'Red', ability: { type: 'sell' } };
CARD_LOOKUP['BasicYellow'] = { kind: 'basicDye', name: 'Basic Yellow', color: 'Yellow', ability: { type: 'sell' } };
CARD_LOOKUP['BasicBlue'] = { kind: 'basicDye', name: 'Basic Blue', color: 'Blue', ability: { type: 'sell' } };

CARD_LOOKUP['Kermes'] = DYE_CARDS[0];
CARD_LOOKUP['Weld'] = DYE_CARDS[1];
CARD_LOOKUP['Woad'] = DYE_CARDS[2];
CARD_LOOKUP['Lac'] = DYE_CARDS[3];
CARD_LOOKUP['Brazilwood'] = DYE_CARDS[4];
CARD_LOOKUP['Pomegranate'] = DYE_CARDS[5];
CARD_LOOKUP['Sumac'] = DYE_CARDS[6];
CARD_LOOKUP['Elderberry'] = DYE_CARDS[7];
CARD_LOOKUP['Turnsole'] = DYE_CARDS[8];
CARD_LOOKUP['Madder'] = DYE_CARDS[9];
CARD_LOOKUP['Turmeric'] = DYE_CARDS[10];
CARD_LOOKUP['DyersGreenweed'] = DYE_CARDS[11];
CARD_LOOKUP['Verdigris'] = DYE_CARDS[12];
CARD_LOOKUP['Orchil'] = DYE_CARDS[13];
CARD_LOOKUP['Logwood'] = DYE_CARDS[14];
CARD_LOOKUP['VermilionDye'] = DYE_CARDS[15];
CARD_LOOKUP['Saffron'] = DYE_CARDS[16];
CARD_LOOKUP['PersianBerries'] = DYE_CARDS[17];
CARD_LOOKUP['Azurite'] = DYE_CARDS[18];
CARD_LOOKUP['IndigoDye'] = DYE_CARDS[19];
CARD_LOOKUP['Cochineal'] = DYE_CARDS[20];

CARD_LOOKUP['StarterCeramics'] = MATERIAL_CARDS[0];
CARD_LOOKUP['StarterPaintings'] = MATERIAL_CARDS[1];
CARD_LOOKUP['StarterTextiles'] = MATERIAL_CARDS[2];

CARD_LOOKUP['TerraCotta'] = DRAFT_MATERIAL_CARDS[0];
CARD_LOOKUP['OchreWare'] = DRAFT_MATERIAL_CARDS[1];
CARD_LOOKUP['CobaltWare'] = DRAFT_MATERIAL_CARDS[2];
CARD_LOOKUP['CinnabarCanvas'] = DRAFT_MATERIAL_CARDS[3];
CARD_LOOKUP['OrpimentCanvas'] = DRAFT_MATERIAL_CARDS[4];
CARD_LOOKUP['UltramarineCanvas'] = DRAFT_MATERIAL_CARDS[5];
CARD_LOOKUP['AlizarinFabric'] = DRAFT_MATERIAL_CARDS[6];
CARD_LOOKUP['FusticFabric'] = DRAFT_MATERIAL_CARDS[7];
CARD_LOOKUP['PastelFabric'] = DRAFT_MATERIAL_CARDS[8];
CARD_LOOKUP['ClayCanvas'] = DRAFT_MATERIAL_CARDS[9];
CARD_LOOKUP['ClayFabric'] = DRAFT_MATERIAL_CARDS[10];
CARD_LOOKUP['CanvasFabric'] = DRAFT_MATERIAL_CARDS[11];

CARD_LOOKUP['Alum'] = ACTION_CARDS[0];
CARD_LOOKUP['CreamOfTartar'] = ACTION_CARDS[1];
CARD_LOOKUP['GumArabic'] = ACTION_CARDS[2];
CARD_LOOKUP['Potash'] = ACTION_CARDS[3];
CARD_LOOKUP['LinseedOil'] = ACTION_CARDS[4];
CARD_LOOKUP['Vinegar'] = ACTION_CARDS[5];
CARD_LOOKUP['Chalk'] = CHALK_CARD;

const SELL_CARD_LOOKUP: Record<string, SellCardData> = {};
SELL_CARD_LOOKUP['Textiles2Vermilion'] = SELL_CARDS[0];
SELL_CARD_LOOKUP['Textiles2Amber'] = SELL_CARDS[1];
SELL_CARD_LOOKUP['Textiles2Chartreuse'] = SELL_CARDS[2];
SELL_CARD_LOOKUP['Textiles2Teal'] = SELL_CARDS[3];
SELL_CARD_LOOKUP['Textiles2Indigo'] = SELL_CARDS[4];
SELL_CARD_LOOKUP['Textiles2Magenta'] = SELL_CARDS[5];
SELL_CARD_LOOKUP['Textiles2OrangeRed'] = SELL_CARDS[6];
SELL_CARD_LOOKUP['Textiles2OrangeYellow'] = SELL_CARDS[7];
SELL_CARD_LOOKUP['Textiles2OrangeBlue'] = SELL_CARDS[8];
SELL_CARD_LOOKUP['Textiles2GreenRed'] = SELL_CARDS[9];
SELL_CARD_LOOKUP['Textiles2GreenYellow'] = SELL_CARDS[10];
SELL_CARD_LOOKUP['Textiles2GreenBlue'] = SELL_CARDS[11];
SELL_CARD_LOOKUP['Textiles2PurpleRed'] = SELL_CARDS[12];
SELL_CARD_LOOKUP['Textiles2PurpleYellow'] = SELL_CARDS[13];
SELL_CARD_LOOKUP['Textiles2PurpleBlue'] = SELL_CARDS[14];
SELL_CARD_LOOKUP['Textiles2RedRedRed'] = SELL_CARDS[15];
SELL_CARD_LOOKUP['Textiles2YellowYellowYellow'] = SELL_CARDS[16];
SELL_CARD_LOOKUP['Textiles2BlueBlueBlue'] = SELL_CARDS[17];
SELL_CARD_LOOKUP['Ceramics3VermilionRed'] = SELL_CARDS[18];
SELL_CARD_LOOKUP['Ceramics3VermilionYellow'] = SELL_CARDS[19];
SELL_CARD_LOOKUP['Ceramics3VermilionBlue'] = SELL_CARDS[20];
SELL_CARD_LOOKUP['Ceramics3AmberRed'] = SELL_CARDS[21];
SELL_CARD_LOOKUP['Ceramics3AmberYellow'] = SELL_CARDS[22];
SELL_CARD_LOOKUP['Ceramics3AmberBlue'] = SELL_CARDS[23];
SELL_CARD_LOOKUP['Ceramics3ChartreuseRed'] = SELL_CARDS[24];
SELL_CARD_LOOKUP['Ceramics3ChartreuseYellow'] = SELL_CARDS[25];
SELL_CARD_LOOKUP['Ceramics3ChartreuseBlue'] = SELL_CARDS[26];
SELL_CARD_LOOKUP['Ceramics3TealRed'] = SELL_CARDS[27];
SELL_CARD_LOOKUP['Ceramics3TealYellow'] = SELL_CARDS[28];
SELL_CARD_LOOKUP['Ceramics3TealBlue'] = SELL_CARDS[29];
SELL_CARD_LOOKUP['Ceramics3IndigoRed'] = SELL_CARDS[30];
SELL_CARD_LOOKUP['Ceramics3IndigoYellow'] = SELL_CARDS[31];
SELL_CARD_LOOKUP['Ceramics3IndigoBlue'] = SELL_CARDS[32];
SELL_CARD_LOOKUP['Ceramics3MagentaRed'] = SELL_CARDS[33];
SELL_CARD_LOOKUP['Ceramics3MagentaYellow'] = SELL_CARDS[34];
SELL_CARD_LOOKUP['Ceramics3MagentaBlue'] = SELL_CARDS[35];
SELL_CARD_LOOKUP['Paintings4VermilionOrange'] = SELL_CARDS[36];
SELL_CARD_LOOKUP['Paintings4VermilionGreen'] = SELL_CARDS[37];
SELL_CARD_LOOKUP['Paintings4VermilionPurple'] = SELL_CARDS[38];
SELL_CARD_LOOKUP['Paintings4AmberOrange'] = SELL_CARDS[39];
SELL_CARD_LOOKUP['Paintings4AmberGreen'] = SELL_CARDS[40];
SELL_CARD_LOOKUP['Paintings4AmberPurple'] = SELL_CARDS[41];
SELL_CARD_LOOKUP['Paintings4ChartreuseOrange'] = SELL_CARDS[42];
SELL_CARD_LOOKUP['Paintings4ChartreuseGreen'] = SELL_CARDS[43];
SELL_CARD_LOOKUP['Paintings4ChartreusePurple'] = SELL_CARDS[44];
SELL_CARD_LOOKUP['Paintings4TealOrange'] = SELL_CARDS[45];
SELL_CARD_LOOKUP['Paintings4TealGreen'] = SELL_CARDS[46];
SELL_CARD_LOOKUP['Paintings4TealPurple'] = SELL_CARDS[47];
SELL_CARD_LOOKUP['Paintings4IndigoOrange'] = SELL_CARDS[48];
SELL_CARD_LOOKUP['Paintings4IndigoGreen'] = SELL_CARDS[49];
SELL_CARD_LOOKUP['Paintings4IndigoPurple'] = SELL_CARDS[50];
SELL_CARD_LOOKUP['Paintings4MagentaOrange'] = SELL_CARDS[51];
SELL_CARD_LOOKUP['Paintings4MagentaGreen'] = SELL_CARDS[52];
SELL_CARD_LOOKUP['Paintings4MagentaPurple'] = SELL_CARDS[53];

export function getCardData(card: Card): AnyCardData {
  return CARD_LOOKUP[card];
}

export function getSellCardData(sellCard: SellCard): SellCardData {
  return SELL_CARD_LOOKUP[sellCard];
}

export function getAnyCardData(card: string): AnyCardData {
  return CARD_LOOKUP[card] ?? SELL_CARD_LOOKUP[card];
}

export function getCardColors(card: string): Color[] {
  const data = getAnyCardData(card);
  if (!data) return [];
  switch (data.kind) {
    case 'dye': return data.colors;
    case 'basicDye': return [data.color];
    case 'material': return data.color ? Array(data.colorCount ?? 1).fill(data.color) : [];
    case 'action': return [];
    case 'sellCard': return [];
  }
}

export const DRAFT_COPY_COUNTS: Record<string, number> = {};
DRAFT_COPY_COUNTS['Lac'] = 3;
DRAFT_COPY_COUNTS['Brazilwood'] = 3;
DRAFT_COPY_COUNTS['Pomegranate'] = 3;
DRAFT_COPY_COUNTS['Sumac'] = 3;
DRAFT_COPY_COUNTS['Elderberry'] = 3;
DRAFT_COPY_COUNTS['Turnsole'] = 3;
DRAFT_COPY_COUNTS['Madder'] = 3;
DRAFT_COPY_COUNTS['Turmeric'] = 3;
DRAFT_COPY_COUNTS['Dyer\'s Greenweed'] = 3;
DRAFT_COPY_COUNTS['Verdigris'] = 3;
DRAFT_COPY_COUNTS['Orchil'] = 3;
DRAFT_COPY_COUNTS['Logwood'] = 3;
DRAFT_COPY_COUNTS['Vermilion'] = 3;
DRAFT_COPY_COUNTS['Saffron'] = 3;
DRAFT_COPY_COUNTS['Persian Berries'] = 3;
DRAFT_COPY_COUNTS['Azurite'] = 3;
DRAFT_COPY_COUNTS['Indigo'] = 3;
DRAFT_COPY_COUNTS['Cochineal'] = 3;
DRAFT_COPY_COUNTS['Terra Cotta'] = 1;
DRAFT_COPY_COUNTS['Ochre Ware'] = 1;
DRAFT_COPY_COUNTS['Cobalt Ware'] = 1;
DRAFT_COPY_COUNTS['Cinnabar & Canvas'] = 1;
DRAFT_COPY_COUNTS['Orpiment & Canvas'] = 1;
DRAFT_COPY_COUNTS['Ultramarine & Canvas'] = 1;
DRAFT_COPY_COUNTS['Alizarin & Fabric'] = 1;
DRAFT_COPY_COUNTS['Fustic & Fabric'] = 1;
DRAFT_COPY_COUNTS['Pastel & Fabric'] = 1;
DRAFT_COPY_COUNTS['Clay & Canvas'] = 1;
DRAFT_COPY_COUNTS['Clay & Fabric'] = 1;
DRAFT_COPY_COUNTS['Canvas & Fabric'] = 1;
DRAFT_COPY_COUNTS['Alum'] = 4;
DRAFT_COPY_COUNTS['Cream of Tartar'] = 4;
DRAFT_COPY_COUNTS['Gum Arabic'] = 4;
DRAFT_COPY_COUNTS['Potash'] = 4;
DRAFT_COPY_COUNTS['Linseed Oil'] = 4;
DRAFT_COPY_COUNTS['Vinegar'] = 4;

export function getDraftCopies(name: string): number {
  return DRAFT_COPY_COUNTS[name] ?? 1;
}

export interface CardCategory {
  label: string;
  cardNames: string[];
  totalCopies: number;
}

export const DRAFT_CARD_CATEGORIES: CardCategory[] = [
  { label: 'Pure Primary Dyes', cardNames: [], totalCopies: 0 },
  { label: 'Primary Dyes', cardNames: ['Lac', 'Brazilwood', 'Pomegranate', 'Sumac', 'Elderberry', 'Turnsole'], totalCopies: 18 },
  { label: 'Secondary Dyes', cardNames: ['Madder', 'Turmeric', 'Dyer\'s Greenweed', 'Verdigris', 'Orchil', 'Logwood'], totalCopies: 18 },
  { label: 'Tertiary Dyes', cardNames: ['Vermilion', 'Saffron', 'Persian Berries', 'Azurite', 'Indigo', 'Cochineal'], totalCopies: 18 },
  { label: 'Action Cards', cardNames: ['Alum', 'Cream of Tartar', 'Gum Arabic', 'Potash', 'Linseed Oil', 'Vinegar'], totalCopies: 24 },
  { label: 'Double Materials', cardNames: [], totalCopies: 0 },
  { label: 'Material + Color', cardNames: ['Terra Cotta', 'Ochre Ware', 'Cobalt Ware', 'Cinnabar & Canvas', 'Orpiment & Canvas', 'Ultramarine & Canvas', 'Alizarin & Fabric', 'Fustic & Fabric', 'Pastel & Fabric'], totalCopies: 9 },
  { label: 'Dual Materials', cardNames: ['Clay & Canvas', 'Clay & Fabric', 'Canvas & Fabric'], totalCopies: 3 },
];

export function getStarterCardCategories(numPlayers: number): CardCategory[] {
  const starterDyeNames = ['Basic Red', 'Basic Yellow', 'Basic Blue'];
  const starterMaterialNames = ['Ceramics', 'Paintings', 'Textiles'];
  return [
    { label: 'Starter Dyes', cardNames: starterDyeNames, totalCopies: starterDyeNames.length * numPlayers },
    { label: 'Starter Materials', cardNames: starterMaterialNames, totalCopies: starterMaterialNames.length * numPlayers },
    { label: 'Chalk', cardNames: ['Chalk'], totalCopies: 1 * numPlayers },
  ];
}
