// AUTO-GENERATED by colori-wasm/build.rs — do not edit by hand
import type { Card, BuyerCard, Color, AnyCardData, DyeCardData, BasicDyeCardData, MaterialCardData, ActionCardData, BuyerCardData } from './types';

export const DYE_CARDS: DyeCardData[] = [
  {
    kind: 'dye',
    name: 'Kermes',
    colors: ['Red', 'Red', 'Red'],
    ability: { type: 'mixColors', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Weld',
    colors: ['Yellow', 'Yellow', 'Yellow'],
    ability: { type: 'mixColors', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Woad',
    colors: ['Blue', 'Blue', 'Blue'],
    ability: { type: 'mixColors', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Lac',
    colors: ['Red', 'Red', 'Yellow'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Brazilwood',
    colors: ['Red', 'Red', 'Blue'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Pomegranate',
    colors: ['Yellow', 'Yellow', 'Red'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Sumac',
    colors: ['Yellow', 'Yellow', 'Blue'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Elderberry',
    colors: ['Blue', 'Blue', 'Red'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Turnsole',
    colors: ['Blue', 'Blue', 'Yellow'],
    ability: { type: 'mixColors', count: 2 },
  },
  {
    kind: 'dye',
    name: 'Madder',
    colors: ['Orange', 'Red'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Turmeric',
    colors: ['Orange', 'Yellow'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Dyer\'s Greenweed',
    colors: ['Green', 'Yellow'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Verdigris',
    colors: ['Green', 'Blue'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Orchil',
    colors: ['Purple', 'Red'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Logwood',
    colors: ['Purple', 'Blue'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'dye',
    name: 'Vermilion',
    colors: ['Vermilion'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Saffron',
    colors: ['Amber'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Persian Berries',
    colors: ['Chartreuse'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Azurite',
    colors: ['Teal'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Indigo',
    colors: ['Indigo'],
    ability: { type: 'sell' },
  },
  {
    kind: 'dye',
    name: 'Cochineal',
    colors: ['Magenta'],
    ability: { type: 'sell' },
  },
];

export const MATERIAL_CARDS: MaterialCardData[] = [
  {
    kind: 'material',
    name: 'Ceramics',
    materialTypes: ['Ceramics'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'material',
    name: 'Paintings',
    materialTypes: ['Paintings'],
    ability: { type: 'workshop', count: 3 },
  },
  {
    kind: 'material',
    name: 'Textiles',
    materialTypes: ['Textiles'],
    ability: { type: 'workshop', count: 3 },
  },
];

export const DRAFT_MATERIAL_CARDS: MaterialCardData[] = [
  {
    kind: 'material',
    name: 'Fine Ceramics',
    materialTypes: ['Ceramics', 'Ceramics'],
    ability: { type: 'destroyCards', count: 1 },
  },
  {
    kind: 'material',
    name: 'Fine Paintings',
    materialTypes: ['Paintings', 'Paintings'],
    ability: { type: 'destroyCards', count: 1 },
  },
  {
    kind: 'material',
    name: 'Fine Textiles',
    materialTypes: ['Textiles', 'Textiles'],
    ability: { type: 'destroyCards', count: 1 },
  },
  {
    kind: 'material',
    name: 'Terra Cotta',
    materialTypes: ['Ceramics'],
    colorPip: 'Red',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Ochre Ware',
    materialTypes: ['Ceramics'],
    colorPip: 'Yellow',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Cobalt Ware',
    materialTypes: ['Ceramics'],
    colorPip: 'Blue',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Cinnabar & Canvas',
    materialTypes: ['Paintings'],
    colorPip: 'Red',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Orpiment & Canvas',
    materialTypes: ['Paintings'],
    colorPip: 'Yellow',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Ultramarine & Canvas',
    materialTypes: ['Paintings'],
    colorPip: 'Blue',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Alizarin & Fabric',
    materialTypes: ['Textiles'],
    colorPip: 'Red',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Fustic & Fabric',
    materialTypes: ['Textiles'],
    colorPip: 'Yellow',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Pastel & Fabric',
    materialTypes: ['Textiles'],
    colorPip: 'Blue',
    ability: { type: 'workshop', count: 2 },
  },
  {
    kind: 'material',
    name: 'Clay & Canvas',
    materialTypes: ['Ceramics', 'Paintings'],
    ability: { type: 'destroyCards', count: 1 },
  },
  {
    kind: 'material',
    name: 'Clay & Fabric',
    materialTypes: ['Ceramics', 'Textiles'],
    ability: { type: 'destroyCards', count: 1 },
  },
  {
    kind: 'material',
    name: 'Canvas & Fabric',
    materialTypes: ['Paintings', 'Textiles'],
    ability: { type: 'destroyCards', count: 1 },
  },
];

export const BASIC_DYE_CARDS: BasicDyeCardData[] = [
  {
    kind: 'basicDye',
    name: 'Basic Red',
    color: 'Red',
    ability: { type: 'sell' },
  },
  {
    kind: 'basicDye',
    name: 'Basic Yellow',
    color: 'Yellow',
    ability: { type: 'sell' },
  },
  {
    kind: 'basicDye',
    name: 'Basic Blue',
    color: 'Blue',
    ability: { type: 'sell' },
  },
];

export const ACTION_CARDS: ActionCardData[] = [
  {
    kind: 'action',
    name: 'Alum',
    ability: { type: 'destroyCards', count: 1 },
    workshopAbilities: [{ type: 'gainDucats', count: 1 }],
  },
  {
    kind: 'action',
    name: 'Cream of Tartar',
    ability: { type: 'workshop', count: 2 },
    workshopAbilities: [{ type: 'drawCards', count: 3 }],
  },
  {
    kind: 'action',
    name: 'Gum Arabic',
    ability: { type: 'destroyCards', count: 1 },
    workshopAbilities: [{ type: 'gainSecondary' }],
  },
  {
    kind: 'action',
    name: 'Potash',
    ability: { type: 'drawCards', count: 2 },
    workshopAbilities: [{ type: 'workshop', count: 3 }],
  },
];

export const PRIMARIES: Color[] = ['Vermilion', 'Amber', 'Chartreuse', 'Teal', 'Indigo', 'Magenta'];
export const SECONDARIES: Color[] = ['Orange', 'Green', 'Purple'];
export const TERTIARIES: Color[] = ['Red', 'Yellow', 'Blue'];

export const CHALK_CARD: ActionCardData = {
  kind: 'action',
  name: 'Chalk',
  ability: { type: 'sell' },
  workshopAbilities: [{ type: 'gainPrimary' }],
};

export const BUYER_CARDS: BuyerCardData[] = [
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Vermilion'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Amber'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Chartreuse'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Teal'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Indigo'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Magenta'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Orange', 'Red'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Orange', 'Yellow'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Orange', 'Blue'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Green', 'Red'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Green', 'Yellow'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Green', 'Blue'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Purple', 'Red'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Purple', 'Yellow'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Purple', 'Blue'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Red', 'Red', 'Red'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Yellow', 'Yellow', 'Yellow'] },
  { kind: 'buyer', stars: 2, requiredMaterial: 'Textiles', colorCost: ['Blue', 'Blue', 'Blue'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Vermilion', 'Red'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Vermilion', 'Yellow'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Vermilion', 'Blue'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Amber', 'Red'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Amber', 'Yellow'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Amber', 'Blue'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Chartreuse', 'Red'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Chartreuse', 'Yellow'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Chartreuse', 'Blue'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Teal', 'Red'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Teal', 'Yellow'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Teal', 'Blue'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Indigo', 'Red'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Indigo', 'Yellow'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Indigo', 'Blue'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Magenta', 'Red'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Magenta', 'Yellow'] },
  { kind: 'buyer', stars: 3, requiredMaterial: 'Ceramics', colorCost: ['Magenta', 'Blue'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Vermilion', 'Orange'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Vermilion', 'Green'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Vermilion', 'Purple'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Amber', 'Orange'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Amber', 'Green'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Amber', 'Purple'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Chartreuse', 'Orange'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Chartreuse', 'Green'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Chartreuse', 'Purple'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Teal', 'Orange'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Teal', 'Green'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Teal', 'Purple'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Indigo', 'Orange'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Indigo', 'Green'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Indigo', 'Purple'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Magenta', 'Orange'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Magenta', 'Green'] },
  { kind: 'buyer', stars: 4, requiredMaterial: 'Paintings', colorCost: ['Magenta', 'Purple'] },
];

const CARD_LOOKUP: Record<string, AnyCardData> = {};

CARD_LOOKUP['BasicRed'] = { kind: 'basicDye', name: 'Basic Red', color: 'Red', ability: { type: 'sell' } };
CARD_LOOKUP['BasicYellow'] = { kind: 'basicDye', name: 'Basic Yellow', color: 'Yellow', ability: { type: 'sell' } };
CARD_LOOKUP['BasicBlue'] = { kind: 'basicDye', name: 'Basic Blue', color: 'Blue', ability: { type: 'sell' } };

CARD_LOOKUP['Kermes'] = DYE_CARDS[0];
CARD_LOOKUP['Weld'] = DYE_CARDS[1];
CARD_LOOKUP['Woad'] = DYE_CARDS[2];
CARD_LOOKUP['Lac'] = DYE_CARDS[3];
CARD_LOOKUP['Brazilwood'] = DYE_CARDS[4];
CARD_LOOKUP['Pomegranate'] = DYE_CARDS[5];
CARD_LOOKUP['Sumac'] = DYE_CARDS[6];
CARD_LOOKUP['Elderberry'] = DYE_CARDS[7];
CARD_LOOKUP['Turnsole'] = DYE_CARDS[8];
CARD_LOOKUP['Madder'] = DYE_CARDS[9];
CARD_LOOKUP['Turmeric'] = DYE_CARDS[10];
CARD_LOOKUP['DyersGreenweed'] = DYE_CARDS[11];
CARD_LOOKUP['Verdigris'] = DYE_CARDS[12];
CARD_LOOKUP['Orchil'] = DYE_CARDS[13];
CARD_LOOKUP['Logwood'] = DYE_CARDS[14];
CARD_LOOKUP['VermilionDye'] = DYE_CARDS[15];
CARD_LOOKUP['Saffron'] = DYE_CARDS[16];
CARD_LOOKUP['PersianBerries'] = DYE_CARDS[17];
CARD_LOOKUP['Azurite'] = DYE_CARDS[18];
CARD_LOOKUP['IndigoDye'] = DYE_CARDS[19];
CARD_LOOKUP['Cochineal'] = DYE_CARDS[20];

CARD_LOOKUP['StarterCeramics'] = MATERIAL_CARDS[0];
CARD_LOOKUP['StarterPaintings'] = MATERIAL_CARDS[1];
CARD_LOOKUP['StarterTextiles'] = MATERIAL_CARDS[2];

CARD_LOOKUP['FineCeramics'] = DRAFT_MATERIAL_CARDS[0];
CARD_LOOKUP['FinePaintings'] = DRAFT_MATERIAL_CARDS[1];
CARD_LOOKUP['FineTextiles'] = DRAFT_MATERIAL_CARDS[2];
CARD_LOOKUP['TerraCotta'] = DRAFT_MATERIAL_CARDS[3];
CARD_LOOKUP['OchreWare'] = DRAFT_MATERIAL_CARDS[4];
CARD_LOOKUP['CobaltWare'] = DRAFT_MATERIAL_CARDS[5];
CARD_LOOKUP['CinnabarCanvas'] = DRAFT_MATERIAL_CARDS[6];
CARD_LOOKUP['OrpimentCanvas'] = DRAFT_MATERIAL_CARDS[7];
CARD_LOOKUP['UltramarineCanvas'] = DRAFT_MATERIAL_CARDS[8];
CARD_LOOKUP['AlizarinFabric'] = DRAFT_MATERIAL_CARDS[9];
CARD_LOOKUP['FusticFabric'] = DRAFT_MATERIAL_CARDS[10];
CARD_LOOKUP['PastelFabric'] = DRAFT_MATERIAL_CARDS[11];
CARD_LOOKUP['ClayCanvas'] = DRAFT_MATERIAL_CARDS[12];
CARD_LOOKUP['ClayFabric'] = DRAFT_MATERIAL_CARDS[13];
CARD_LOOKUP['CanvasFabric'] = DRAFT_MATERIAL_CARDS[14];

CARD_LOOKUP['Alum'] = ACTION_CARDS[0];
CARD_LOOKUP['CreamOfTartar'] = ACTION_CARDS[1];
CARD_LOOKUP['GumArabic'] = ACTION_CARDS[2];
CARD_LOOKUP['Potash'] = ACTION_CARDS[3];
CARD_LOOKUP['Chalk'] = CHALK_CARD;

const BUYER_LOOKUP: Record<string, BuyerCardData> = {};
BUYER_LOOKUP['Textiles2Vermilion'] = BUYER_CARDS[0];
BUYER_LOOKUP['Textiles2Amber'] = BUYER_CARDS[1];
BUYER_LOOKUP['Textiles2Chartreuse'] = BUYER_CARDS[2];
BUYER_LOOKUP['Textiles2Teal'] = BUYER_CARDS[3];
BUYER_LOOKUP['Textiles2Indigo'] = BUYER_CARDS[4];
BUYER_LOOKUP['Textiles2Magenta'] = BUYER_CARDS[5];
BUYER_LOOKUP['Textiles2OrangeRed'] = BUYER_CARDS[6];
BUYER_LOOKUP['Textiles2OrangeYellow'] = BUYER_CARDS[7];
BUYER_LOOKUP['Textiles2OrangeBlue'] = BUYER_CARDS[8];
BUYER_LOOKUP['Textiles2GreenRed'] = BUYER_CARDS[9];
BUYER_LOOKUP['Textiles2GreenYellow'] = BUYER_CARDS[10];
BUYER_LOOKUP['Textiles2GreenBlue'] = BUYER_CARDS[11];
BUYER_LOOKUP['Textiles2PurpleRed'] = BUYER_CARDS[12];
BUYER_LOOKUP['Textiles2PurpleYellow'] = BUYER_CARDS[13];
BUYER_LOOKUP['Textiles2PurpleBlue'] = BUYER_CARDS[14];
BUYER_LOOKUP['Textiles2RedRedRed'] = BUYER_CARDS[15];
BUYER_LOOKUP['Textiles2YellowYellowYellow'] = BUYER_CARDS[16];
BUYER_LOOKUP['Textiles2BlueBlueBlue'] = BUYER_CARDS[17];
BUYER_LOOKUP['Ceramics3VermilionRed'] = BUYER_CARDS[18];
BUYER_LOOKUP['Ceramics3VermilionYellow'] = BUYER_CARDS[19];
BUYER_LOOKUP['Ceramics3VermilionBlue'] = BUYER_CARDS[20];
BUYER_LOOKUP['Ceramics3AmberRed'] = BUYER_CARDS[21];
BUYER_LOOKUP['Ceramics3AmberYellow'] = BUYER_CARDS[22];
BUYER_LOOKUP['Ceramics3AmberBlue'] = BUYER_CARDS[23];
BUYER_LOOKUP['Ceramics3ChartreuseRed'] = BUYER_CARDS[24];
BUYER_LOOKUP['Ceramics3ChartreuseYellow'] = BUYER_CARDS[25];
BUYER_LOOKUP['Ceramics3ChartreuseBlue'] = BUYER_CARDS[26];
BUYER_LOOKUP['Ceramics3TealRed'] = BUYER_CARDS[27];
BUYER_LOOKUP['Ceramics3TealYellow'] = BUYER_CARDS[28];
BUYER_LOOKUP['Ceramics3TealBlue'] = BUYER_CARDS[29];
BUYER_LOOKUP['Ceramics3IndigoRed'] = BUYER_CARDS[30];
BUYER_LOOKUP['Ceramics3IndigoYellow'] = BUYER_CARDS[31];
BUYER_LOOKUP['Ceramics3IndigoBlue'] = BUYER_CARDS[32];
BUYER_LOOKUP['Ceramics3MagentaRed'] = BUYER_CARDS[33];
BUYER_LOOKUP['Ceramics3MagentaYellow'] = BUYER_CARDS[34];
BUYER_LOOKUP['Ceramics3MagentaBlue'] = BUYER_CARDS[35];
BUYER_LOOKUP['Paintings4VermilionOrange'] = BUYER_CARDS[36];
BUYER_LOOKUP['Paintings4VermilionGreen'] = BUYER_CARDS[37];
BUYER_LOOKUP['Paintings4VermilionPurple'] = BUYER_CARDS[38];
BUYER_LOOKUP['Paintings4AmberOrange'] = BUYER_CARDS[39];
BUYER_LOOKUP['Paintings4AmberGreen'] = BUYER_CARDS[40];
BUYER_LOOKUP['Paintings4AmberPurple'] = BUYER_CARDS[41];
BUYER_LOOKUP['Paintings4ChartreuseOrange'] = BUYER_CARDS[42];
BUYER_LOOKUP['Paintings4ChartreuseGreen'] = BUYER_CARDS[43];
BUYER_LOOKUP['Paintings4ChartreusePurple'] = BUYER_CARDS[44];
BUYER_LOOKUP['Paintings4TealOrange'] = BUYER_CARDS[45];
BUYER_LOOKUP['Paintings4TealGreen'] = BUYER_CARDS[46];
BUYER_LOOKUP['Paintings4TealPurple'] = BUYER_CARDS[47];
BUYER_LOOKUP['Paintings4IndigoOrange'] = BUYER_CARDS[48];
BUYER_LOOKUP['Paintings4IndigoGreen'] = BUYER_CARDS[49];
BUYER_LOOKUP['Paintings4IndigoPurple'] = BUYER_CARDS[50];
BUYER_LOOKUP['Paintings4MagentaOrange'] = BUYER_CARDS[51];
BUYER_LOOKUP['Paintings4MagentaGreen'] = BUYER_CARDS[52];
BUYER_LOOKUP['Paintings4MagentaPurple'] = BUYER_CARDS[53];

export function getCardData(card: Card): AnyCardData {
  return CARD_LOOKUP[card];
}

export function getBuyerData(buyer: BuyerCard): BuyerCardData {
  return BUYER_LOOKUP[buyer];
}

export function getAnyCardData(card: string): AnyCardData {
  return CARD_LOOKUP[card] ?? BUYER_LOOKUP[card];
}

export function getCardPips(card: string): Color[] {
  const data = getAnyCardData(card);
  if (!data) return [];
  switch (data.kind) {
    case 'dye': return data.colors;
    case 'basicDye': return [data.color];
    case 'material': return data.colorPip ? [data.colorPip] : [];
    case 'action': return [];
    case 'buyer': return [];
  }
}

export const DRAFT_COPY_COUNTS: Record<string, number> = {};
DRAFT_COPY_COUNTS['Kermes'] = 4;
DRAFT_COPY_COUNTS['Weld'] = 4;
DRAFT_COPY_COUNTS['Woad'] = 4;
DRAFT_COPY_COUNTS['Lac'] = 4;
DRAFT_COPY_COUNTS['Brazilwood'] = 4;
DRAFT_COPY_COUNTS['Pomegranate'] = 4;
DRAFT_COPY_COUNTS['Sumac'] = 4;
DRAFT_COPY_COUNTS['Elderberry'] = 4;
DRAFT_COPY_COUNTS['Turnsole'] = 4;
DRAFT_COPY_COUNTS['Madder'] = 4;
DRAFT_COPY_COUNTS['Turmeric'] = 4;
DRAFT_COPY_COUNTS['Dyer\'s Greenweed'] = 4;
DRAFT_COPY_COUNTS['Verdigris'] = 4;
DRAFT_COPY_COUNTS['Orchil'] = 4;
DRAFT_COPY_COUNTS['Logwood'] = 4;
DRAFT_COPY_COUNTS['Vermilion'] = 4;
DRAFT_COPY_COUNTS['Saffron'] = 4;
DRAFT_COPY_COUNTS['Persian Berries'] = 4;
DRAFT_COPY_COUNTS['Azurite'] = 4;
DRAFT_COPY_COUNTS['Indigo'] = 4;
DRAFT_COPY_COUNTS['Cochineal'] = 4;
DRAFT_COPY_COUNTS['Fine Ceramics'] = 1;
DRAFT_COPY_COUNTS['Fine Paintings'] = 1;
DRAFT_COPY_COUNTS['Fine Textiles'] = 1;
DRAFT_COPY_COUNTS['Terra Cotta'] = 1;
DRAFT_COPY_COUNTS['Ochre Ware'] = 1;
DRAFT_COPY_COUNTS['Cobalt Ware'] = 1;
DRAFT_COPY_COUNTS['Cinnabar & Canvas'] = 1;
DRAFT_COPY_COUNTS['Orpiment & Canvas'] = 1;
DRAFT_COPY_COUNTS['Ultramarine & Canvas'] = 1;
DRAFT_COPY_COUNTS['Alizarin & Fabric'] = 1;
DRAFT_COPY_COUNTS['Fustic & Fabric'] = 1;
DRAFT_COPY_COUNTS['Pastel & Fabric'] = 1;
DRAFT_COPY_COUNTS['Clay & Canvas'] = 1;
DRAFT_COPY_COUNTS['Clay & Fabric'] = 1;
DRAFT_COPY_COUNTS['Canvas & Fabric'] = 1;
DRAFT_COPY_COUNTS['Alum'] = 4;
DRAFT_COPY_COUNTS['Cream of Tartar'] = 4;
DRAFT_COPY_COUNTS['Gum Arabic'] = 4;
DRAFT_COPY_COUNTS['Potash'] = 4;

export function getDraftCopies(name: string): number {
  return DRAFT_COPY_COUNTS[name] ?? 1;
}

export interface CardCategory {
  label: string;
  cardNames: string[];
  totalCopies: number;
}

export const DRAFT_CARD_CATEGORIES: CardCategory[] = [
  { label: 'Primary Dyes', cardNames: ['Vermilion', 'Saffron', 'Persian Berries', 'Azurite', 'Indigo', 'Cochineal'], totalCopies: 24 },
  { label: 'Secondary Dyes', cardNames: ['Madder', 'Turmeric', 'Dyer\'s Greenweed', 'Verdigris', 'Orchil', 'Logwood'], totalCopies: 24 },
  { label: 'Tertiary Dyes', cardNames: ['Kermes', 'Weld', 'Woad', 'Lac', 'Brazilwood', 'Pomegranate', 'Sumac', 'Elderberry', 'Turnsole'], totalCopies: 36 },
  { label: 'Action Cards', cardNames: ['Alum', 'Cream of Tartar', 'Gum Arabic', 'Potash'], totalCopies: 16 },
  { label: 'Double Materials', cardNames: ['Fine Ceramics', 'Fine Paintings', 'Fine Textiles'], totalCopies: 3 },
  { label: 'Material + Color', cardNames: ['Terra Cotta', 'Ochre Ware', 'Cobalt Ware', 'Cinnabar & Canvas', 'Orpiment & Canvas', 'Ultramarine & Canvas', 'Alizarin & Fabric', 'Fustic & Fabric', 'Pastel & Fabric'], totalCopies: 9 },
  { label: 'Dual Materials', cardNames: ['Clay & Canvas', 'Clay & Fabric', 'Canvas & Fabric'], totalCopies: 3 },
];

export function getStarterCardCategories(numPlayers: number): CardCategory[] {
  const starterDyeNames = ['Basic Red', 'Basic Yellow', 'Basic Blue'];
  const starterMaterialNames = ['Ceramics', 'Paintings', 'Textiles'];
  return [
    { label: 'Starter Dyes', cardNames: starterDyeNames, totalCopies: starterDyeNames.length * numPlayers },
    { label: 'Starter Materials', cardNames: starterMaterialNames, totalCopies: starterMaterialNames.length * numPlayers },
    { label: 'Chalk', cardNames: ['Chalk'], totalCopies: 1 * numPlayers },
  ];
}
